---
- name: Create network interfaces file
  hosts: 'all'
  remote_user: root

  tasks:
  - name: Apply template to /etc/network/interfaces
    template:
      src: templates/interfaces_dell.cfg.j2
      dest: /etc/network/interfaces
      owner: root
      group: root
      mode: 0644

  - name: Apply template to /etc/network/interfaces.d/openstack.cfg
    template:
      src: templates/os-refimpl-devices.cfg.j2
      dest: /etc/network/interfaces.d/openstack.cfg
      owner: root
      group: root
      mode: 0644
      
  - name: Bring up the interfaces
    shell: ifup p3p2 && ifup p3p1 && ifdown p3p1 && ifup em2 && ifup bond1 && ifup bond0 && ifup p3p1 && ifup bond0.200 
    
  - name: Add address to bond0
    command: ip addr add {{ ansible_ssh_host_new }}/22 dev bond0

  - name: Add default route
    command: route add default gw 10.3.72.1 bond0.200
