---

- name: Prepare node disks
  hosts: storage
  remote_user: root
  become: yes
  tasks:
    - name: Install xfsprogs package
      apt:
        name: xfsprogs
        state: present
        update_cache: yes
    - name: Copy script
      copy: src=../scripts/swift-prep-disks.sh dest=/root/ mode=0777
    - name: Copy disks.lst
      copy: src=../scripts/disks.lst dest=/root/ mode=0777
    - name: Execute the script
      shell: /bin/bash /root/swift-prep-disks.sh >> /root/out
      ignore_errors: yes
      become_user: root
